flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icons/logo.jpg'
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: 'assets/icons/logo.jpg'
    background_color: '#47b3e2'
    theme_color: '#47b3e2'
  windows:
    generate: true
    image_path: 'assets/icons/logo.jpg'
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: 'assets/icons/logo.jpg'
